Code cleanup
persistenceOne/persistenceWallet pull request #344
Opened 2021-12-15 10:16 UTC by blackpanther1881

1. Code update.
2. UI updates and ui fixes
3. code cleanup
4. track defect fixes

2021-12-16 11:00 UTC, puneet2019 commented on src/App.js
> +const SENTRY_API = process.env.REACT_APP_SENTRY_API;
make it configurable, default OFF, because we do not want sentry while running wallet locally.

2021-12-16 11:00 UTC, puneet2019 commented on src/App.js
> +        if (localStorage.getItem('loginMode') === 'keplr') {
lets take this string from constants please?

2021-12-16 11:01 UTC, puneet2019 commented on src/App.js
>                  const address = localStorage.getItem("keplerAddress");
all local storage string constants from constants.

2021-12-16 11:13 UTC, puneet2019 commented on src/components/AdvancedFields/index.js
>              if (parseInt(accountNumber) > 4294967295 || parseInt(accountNumber) < 0) {
change this number to max(int) -> 2147483647, has been raised in one of the issues

2021-12-16 11:13 UTC, puneet2019 commented on src/components/AdvancedFields/index.js
>              if (parseInt(addressIndex) > 4294967295 || parseInt(addressIndex) < 0) {
2147483647

2021-12-16 11:13 UTC, puneet2019 commented on src/components/AdvancedFields/index.js
>                                  max={4294967295}
2147483647

2021-12-16 11:13 UTC, puneet2019 commented on src/components/AdvancedFields/index.js
>                                  max={4294967295}
2147483647 and take from constants

2021-12-16 11:13 UTC, puneet2019 commented on src/components/AdvancedFields/index.js
>              if (parseInt(accountNumber) > 4294967295 || parseInt(accountNumber) < 0) {
2147483647 and take from constants

2021-12-16 11:16 UTC, puneet2019 commented on src/components/Fee/index.js
> +                        of {transactions.XprtConversion(localStorage.getItem('fee') * 1)} XPRT is
parseInt instead of quick fixes like * 1
or just append + before a string-number.

5 * +"2"

2021-12-16 11:27 UTC, puneet2019 commented on src/components/RouteNotFound.js
>                                      HELP
internationalisation

2021-12-16 11:32 UTC, puneet2019 commented on src/config.json
> +  "chainID": "test-core-1",
is this being used somewhere?

2021-12-16 11:33 UTC, puneet2019 commented on src/config.json
> +  "chainID": "test-core-1",
looks hardcoded not configurable for mainnet/ other networks

2021-12-16 11:33 UTC, puneet2019 commented on src/config.json
>    "valoperAddressPrefix": "persistence",
valoperAddressPrefix is ... `persistencevaloper`
where is this being used?

2021-12-16 11:36 UTC, puneet2019 commented on src/constants/url.js
> +export const getSendTransactionsUrl = (address, limit, pageNumber) => `${API_URL}/cosmos/tx/v1beta1/txs?events=message.sender='${address}'&order_by=ORDER_BY_DESC&pagination.offset=${limit * pageNumbe
are we using this anywhere?

2021-12-16 11:36 UTC, puneet2019 commented on src/constants/url.js
> +export const getReceiveTransactionsUrl = (address, limit, pageNumber) => `${API_URL}/cosmos/tx/v1beta1/txs?events=transfer.recipient='${address}'&order_by=ORDER_BY_DESC&pagination.offset=${limit * pa
are we using this anymore?

2021-12-17 10:28 UTC, puneet2019 commented on src/utils/validations.js
> +export const passwordValidation = (data) => {
why lower case?

2021-12-17 10:38 UTC, puneet2019 commented on src/containers/ChangeKeyStorePassword/ModalResult.js
> +        const fileName = "KeyStore";
take from constants, let user also name it differently if user wishes.

2021-12-17 10:41 UTC, puneet2019 commented on src/containers/Common/Advanced/AccountIndex.js
> +                max={4294967295}
take from constants, and its 2147483647

2021-12-17 10:41 UTC, puneet2019 commented on src/containers/Common/Advanced/AccountNumber.js
> +                max={4294967295}
take from constants -> 2147483647

2021-12-17 10:42 UTC, puneet2019 commented on src/containers/Common/DashboardHeader.js
> +        const accountNumber = localStorage.getItem('accountNumber');
take item 'accountNumber' etc from constants please

2021-12-17 10:43 UTC, puneet2019 commented on src/containers/Common/DashboardHeader.js
> +                                                    onClick={ledgerShowAddress}>Verify</button>
internationalisation

2021-12-17 10:44 UTC, puneet2019 commented on src/containers/Common/Fee/Gas.js
> +            value: (evt.target.value * 1),
use parseInt or +evt.target.value

2021-12-17 10:45 UTC, puneet2019 commented on src/containers/Common/Fee/Gas.js
> +                <p onClick={handleGas} className="text-center">{!showGasField ? "Advanced" : "Advanced"}
internationalisation `Advanced`

2021-12-17 10:46 UTC, puneet2019 commented on src/containers/Common/Fee/Gas.js
> +                        max={2000000}
take min/max from configuration/ constants* cosmos just increased max to 4000000

2021-12-17 10:46 UTC, puneet2019 commented on src/containers/Common/Fee/Submit.js
> +    let loginMode = localStorage.getItem('loginMode');
`loginMode`, `address` from constants

2021-12-17 10:47 UTC, puneet2019 commented on src/containers/Common/Fee/Submit.js
> +        if (loginMode === "ledger") {
`ledger` from constants. 
because typos are common while using strings directly

2021-12-17 10:48 UTC, puneet2019 commented on src/containers/Common/Fee/index.js
> +                                    value={formatNumber(transactions.XprtConversion((gas.value) * config.lowFee))}/>XPRT
can we also take coinName from constants? 
`XPRT` ?

2021-12-17 10:48 UTC, puneet2019 commented on src/containers/Common/KeyStore/Modal.js
> +    const encryptedMnemonic = localStorage.getItem('encryptedMnemonic');
`encryptedMnemonic` from constants

2021-12-17 10:50 UTC, puneet2019 commented on src/containers/Common/KeyStore/Submit.js
> +    let loginAddress = localStorage.getItem('address');
`address` from constants.

2021-12-17 10:50 UTC, puneet2019 commented on src/containers/Common/ModalVIewAmountDetails/index.js
> +            if (item.denom !== config.coinDenom) {
awesome :) :P

2021-12-17 10:51 UTC, puneet2019 commented on src/containers/Common/ModalViewDelegationDetails/index.js
> +                                                            value={formatNumber(transactions.XprtConversion(delegation.delegations * 1))}/>XPRT
+delegation.delegations

2021-12-17 10:54 UTC, puneet2019 commented on src/containers/Common/ModalViewTxnResponse/index.js
> +    useEffect(() => {
can we do all of them async, I think it causes wallet to be slow

2021-12-17 10:54 UTC, puneet2019 commented on src/containers/Common/ModalViewUnbondDetails/index.js
> +                                                        value={formatNumber(transactions.XprtConversion(entry.balance * 1))}/> XPRT
+ instead of *1

2021-12-17 10:55 UTC, puneet2019 commented on src/containers/Common/ModalViewUnbondDetails/index.js
> +                                                    className="date">{moment(new Date(entry["completionTime"]).toString()).format('dddd MMMM Do YYYY, h:mm:ss a')}</span>
make it a standard function.

2021-12-17 10:56 UTC, puneet2019 commented on src/containers/Common/ModalViewVestingDetails/index.js
> +                                            <td>{transactions.XprtConversion(parseInt(response.baseVestingAccount.originalVesting[0].amount))}</td>
check if [0] exists, might throw out of range errors

2021-12-17 10:57 UTC, puneet2019 commented on src/containers/Common/TokenInfo.js
> +                            <NumberView value={formatNumber(props.transferableAmount)}/> XPRT
XPRT from constants

2021-12-17 10:57 UTC, puneet2019 commented on src/containers/Common/TokenInfo.js
> +                                <NumberView value={formatNumber(props.rewards)}/> XPRT
XPRT from constants

2021-12-17 10:57 UTC, puneet2019 commented on src/containers/Common/TokenInfo.js
> +                            <p className="value" title={props.transferableAmount.toFixed(6)}><span
toFixed( constants.CoinDecimals )

2021-12-17 10:59 UTC, puneet2019 commented on src/containers/CreateWallet/ModalCreateWallet/AdvanceMode.js
>              if (parseInt(accountNumber) > 4294967295 || parseInt(accountNumber) < 0) {
constants and replace this with 2147483647

2021-12-17 10:59 UTC, puneet2019 commented on src/containers/CreateWallet/ModalCreateWallet/AdvanceMode.js
>              if (parseInt(addressIndex) > 4294967295 || parseInt(addressIndex) < 0) {
constants and replace with 2147483647

2021-12-17 11:12 UTC, puneet2019 commented on src/containers/GenerateKeyStore/ModalMnemonic/index.js
> +                        KeyStore Password</p>
internationalisation `Change
                        KeyStore Password`

2021-12-17 11:13 UTC, puneet2019 commented on src/containers/GenerateKeyStore/ModalResult/index.js
> +                    <p>Keystore Successfully downloaded</p>
internationalisation `Keystore Successfully downloaded`

2021-12-17 11:15 UTC, puneet2019 commented on src/containers/KeyStore/GenerateKeyStore/index.js
> +                                        KeyStore Password</p>
internationisation

2021-12-17 11:15 UTC, puneet2019 commented on src/containers/KeyStore/ModalDecryptKeystore/index.js
>              if (parseInt(accountNumber) > 4294967295 || parseInt(accountNumber) < 0) {
change 4294967295 throughout the project for accountNumber and index.

2021-12-17 11:17 UTC, puneet2019 commented on src/containers/SignIn/Keplr/KeplrModal/index.js
> +// import ModalKeplerInstall from "../../../../views/Kepler/ModalKeplerInstall";
remove commented code

2021-12-17 11:17 UTC, puneet2019 commented on src/containers/SignIn/KeyStore/ModalForm/FileInput.js
> +        localStorage.setItem('encryptedMnemonic', file);
`encryptedMnemonic` constants

2021-12-17 11:18 UTC, puneet2019 commented on src/containers/SignIn/Ledger/Advanced/AccountNumber.js
> +    // const token = useSelector((state) => state.send.token.value);
remove commented code

2021-12-17 11:19 UTC, puneet2019 commented on src/containers/SignIn/Ledger/Advanced/index.js
> +        // .advanced-wallet-accordion .card .collapse.show
remove

2021-12-17 11:19 UTC, puneet2019 commented on src/containers/SignIn/Ledger/LedgerModal/index.js
> +                        <p className="fetching">Fetching Address</p>
internationalisation

2021-12-17 11:20 UTC, puneet2019 commented on src/containers/SignIn/index.js
> +            {/*{withKeyStore ?*/}
delete commented code

2021-12-17 11:20 UTC, puneet2019 commented on src/containers/Staking/Validators/DelegatedValidators/index.js
> +    const loginInfo = JSON.parse(localStorage.getItem('loginInfo'));
`loginInfo` constants

2021-12-17 11:21 UTC, puneet2019 commented on src/containers/Staking/Validators/ModalDelegate/Amount.js
> +                    error: ValidateSendAmount(transferableAmount, (evt.target.value * 1))
+

2021-12-17 11:21 UTC, puneet2019 commented on src/containers/Staking/Validators/ModalDelegate/index.js
> +                <h3 className="heading">Delegate {props.moniker}
internationalisation

2021-12-17 11:22 UTC, puneet2019 commented on src/containers/Staking/Validators/ModalReDelegate/ButtonSubmit.js
> +                    onClick={loginInfo.loginMode === "keplr" ? onClickKeplr : onClick}
`keplr` constants

2021-12-17 11:23 UTC, puneet2019 commented on src/containers/Staking/Validators/ModalReDelegate/Validator.js
> +                                        <span className="state inactive">inActive </span>
internationalisation

2021-12-17 11:23 UTC, puneet2019 commented on src/containers/Staking/Validators/ModalReDelegate/index.js
> +    const loginInfo = JSON.parse(localStorage.getItem('loginInfo'));
constants

2021-12-17 11:24 UTC, puneet2019 commented on src/containers/Staking/Validators/ModalValidator/index.js
> +                    <p className="amount-warning text-left"> Warning: Foundation Nodes operate at 100%
internationalisation

2021-12-17 11:25 UTC, puneet2019 commented on src/containers/Staking/Validators/ValidatorsTable.js
> +    const loginInfo = JSON.parse(localStorage.getItem('loginInfo'));
pick from constants loginInfo

2021-12-17 11:27 UTC, puneet2019 commented on src/containers/Wallet/ModalWithDraw/index.js
> +                    <p className="amount-warning">{selectedValidators.error.message !== '' ? "Warning:  Recommend 3 or fewer validators to avoid potential issues." : ""}</p>
internationalisation

2021-12-17 11:29 UTC, puneet2019 commented on src/containers/Wallet/Send/Amount.js
> +                                    className="value">{token.transferableAmount.toLocaleString()} ATOM ( IBC Trace path - {token.tokenItem.denom.path} , denom: {token.tokenItem.denom.baseDenom} )</sp
why atom hardcoded?

2021-12-17 11:30 UTC, puneet2019 commented on src/containers/Wallet/Send/ToAddress.js
> +                Recipient’s address starts with persistence; for example:
internationalisation

2021-12-17 11:32 UTC, puneet2019 commented on src/containers/Wallet/SendIbc/ToAddress.js
> +                Recipient’s address starts with persistence; for example:
internationalisation

2021-12-17 11:42 UTC, puneet2019 commented on src/utils/transactions.js
> +    if (txName === "send") {
since you are passing data.message, i dont think you require the if, else if, else statements for them.
if required change to switch case.

2021-12-17 11:43 UTC, puneet2019 commented on src/store/actions/generateKeyStore.js
> +            // if (responseData.error) {
remove commented code.

2021-12-17 11:48 UTC, puneet2019 commented on src/store/reducers/index.js
> +    if (action.type === 'USER_LOGOUT') {
constants

2021-12-17 11:54 UTC, puneet2019 commented on src/utils/helper.js
> +    } else if (prefix === "osmosis") {
switch case.

2021-12-17 11:55 UTC, puneet2019 commented on src/utils/helper.js
> +    } else if (denom === "uatom") {
config, switchcase

2021-12-17 11:56 UTC, puneet2019 requested changes
mostly its internationalisation, changing account number max amount, taking localstorage keys to constants, parsing numbers using +, or parseInt

2022-01-04 06:21 UTC, puneet2019 commented on src/components/AdvancedFields/index.js
> +                                max={config.maxAccountNumber}
maxAccountIndex for better readability. 
even if constant is same.

2022-01-04 08:53 UTC, blackpanther1881 commented on src/containers/Staking/Validators/DelegatedValidators/index.js
> +    const loginInfo = JSON.parse(localStorage.getItem('loginInfo'));
will take up this later

2022-01-04 08:55 UTC, blackpanther1881 commented on src/utils/transactions.js
> +    if (txName === "send") {
in data.message we are not passing tx name.  changed to switch

2022-01-04 08:55 UTC, blackpanther1881 commented on src/containers/Staking/Validators/ValidatorsTable.js
> +    const loginInfo = JSON.parse(localStorage.getItem('loginInfo'));
will takeup later

2022-01-04 08:56 UTC, blackpanther1881 commented on src/config.json
> +  "chainID": "test-core-1",
removed

2022-01-04 08:57 UTC, blackpanther1881 commented on src/config.json
>    "valoperAddressPrefix": "persistence",
initially we have used in some helper function.

2022-01-04 09:00 UTC, blackpanther1881 commented on src/utils/validations.js
> +export const passwordValidation = (data) => {
CHANGED

2022-01-06 10:59 UTC, puneet2019 commented on src/containers/Common/Advanced/AccountNumber.js
> +                max={config.maxAccountIndex}
Have different constants. 
maxAccountIndex = 2,147,483,647
maxAccountNumber = 2,147,483,647

use respective constants in places

2022-01-06 11:07 UTC, puneet2019 submitted a review, later dismissed

2022-01-07 08:36 UTC, puneet2019 approved these changes

2022-01-07 11:13 UTC, merged